import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
//components
import SideBar from "../components/SideBar";
import DonutChart from "../components/dashboard/DonutChart";
import TransactonsTable from "../components/dashboard/TransactionsTable";
import BarChart from "../components/dashboard/BarChart";
import { LineChart } from "../components/dashboard/LineChart";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-100 h-screen">
        <div className="bg-white h-14 ml-44 text-black flex justify-between items-center">
          <p className="pl-4">Company Name LTD</p>
          <p className="ml-auto">Today</p>
          <p className="px-2">Month</p>
          <p className="pr-4">Year</p>
        </div>
        <div className="flex">
          <SideBar />
        </div>

        <div className="ml-44 mt-4">
          <div className="grid grid-cols-3 ml-3 mr-3">
            <div className="bg-white h-60 shadow-sm rounded-lg">
              <p className="text-center pb-4 pt-2 font-semibold">
                Account Balances
              </p>
              <DonutChart />
            </div>
            <div className="bg-white h-60 ml-6 shadow-sm rounded-lg">
              <p className="text-center pb-4 pt-2 font-semibold">
                Total Money In & Out
              </p>
              <BarChart />
            </div>
            <div className="bg-white h-60 ml-6 shadow-sm rounded-lg">
              <p className="text-center pb-4 pt-2 font-semibold">
                Bank Balance
              </p>
              <LineChart />
            </div>
          </div>

          <div className="">
            <TransactonsTable />
          </div>
        </div>
      </div>
    </>
  );
}
